laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('certificacoes-provence', 'CertificacoesController@provence')->name('certificacoes-provence');
    Route::get('certificacoes-provence/{internal?}', 'CertificacoesController@provencePaginaInterna')->name('provence-interna');
    Route::get('certificacoes-inmetro', 'CertificacoesController@inmetro')->name('certificacoes-inmetro');
    Route::get('certificacoes-inmetro/{internal?}', 'CertificacoesController@inmetroPaginaInterna')->name('inmetro-interna');
    Route::get('certificacoes-de-sistemas', 'CertificacoesController@deSistemas')->name('certificacoes-de-sistemas');
    Route::get('perfil-empresa', 'HomeController@perfilEmpresa')->name('perfil-empresa');
    Route::get('nossos-servicos', 'HomeController@nossosServicos')->name('nossos-servicos');
    Route::get('suporte-e-novidades/documentos-regulamentares', 'NovidadesController@documentosRegulamentares')->name('documentos-regulamentares');
    Route::get('suporte-e-novidades/perguntas-frequentes', 'NovidadesController@perguntasFrequentes')->name('perguntas-frequentes');
    Route::get('suporte-e-novidades/novidades', 'NovidadesController@novidades')->name('informacoes-e-novidades');
    Route::get('novidades/{internal?}', 'NovidadesController@novidadesPaginaInterna')->name('novidades-interna');
    Route::get('fale-conosco', 'FaleConoscoController@index')->name('fale-conosco');
    Route::post('fale-conosco', 'FaleConoscoController@post')->name('fale-conosco-post');
    Route::get('politica-de-privacidade', 'HomeController@politicaDePrivacidade')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');
    Route::post('propostas-post', 'PropostasController@post')->name('propostas-post');
    
    // Idiomas
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if (in_array($idioma, ['pt', 'en'])) {
            Session::put('locale', $idioma);
        }
        return redirect()->back();
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        Route::group(['middleware' => 'admin'], function() {
            /* GENERATED ROUTES */
            Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
            Route::resource('certificacoes-provence', 'CertificacoesProvenceController', ['only' => ['index', 'update']]);
            Route::resource('certificacoes-provence-item', 'CertificacoesProvenceItemController');
            Route::resource('certificacoes-inmetro', 'CertificacoesInmetroController', ['only' => ['index', 'update']]);
            Route::resource('certificacoes-inmetro-item', 'CertificacoesInmetroItemController');
            Route::resource('certificacoes-de-sistemas', 'CertificacoesDeSistemasController', ['only' => ['index', 'update']]);
            Route::resource('perfil-empresa', 'PerfilEmpresaController', ['only' => ['index', 'update']]);
            Route::resource('nossos-servicos', 'NossosServicosController', ['only' => ['index', 'update']]);
            Route::resource('documentos-regulamentares', 'DocumentosRegulamentaresController');
            Route::resource('perguntas-frequentes', 'PerguntasFrequentesController');
            Route::resource('informacoes-e-novidades', 'InformacoesNovidadesController');
            Route::resource('fale-conosco', 'FaleConoscoController', ['only' => ['index', 'update']]);
            Route::resource('depoimentos', 'DepoimentosController');
            Route::resource('propostas', 'PropostasController');
            Route::resource('propostas-configuracoes', 'PropostasConfigController');
            Route::resource('validacao-certificados', 'ValidacaoController');
            Route::resource('certificados', 'CertificadosDeValidacaoController');
            Route::resource('banners', 'BannersController');
            Route::resource('certificado-de-sistemas-imagens', 'CertificadoSistemasImagensController');

            Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

            Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
            Route::resource('contato', 'ContatoController');
            Route::get('contato/recebidos', 'ContatosRecebidosController@index')->name('painel.contato.recebidos');
            Route::resource('recebidos', 'RecebidosController');

            Route::resource('usuarios', 'UsuariosController');
            Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
            Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');

            Route::post('ckeditor-upload', 'PainelController@imageUpload');
            Route::post('order', 'PainelController@order');
            Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

            Route::get('generator', 'GeneratorController@index')->name('generator.index');
            Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
        });
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });

    Route::get('/{slug}', 'ValidacaoController@index')->name('validacao-cliente');
});

laravel/app/Models/PropostasConfig.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PropostasConfig extends Model
{
    protected $table = 'propostas_config';

    protected $guarded = ['id'];
}

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/CertificacoesDeSistemasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Requests\CertificacoesRequest;
use App\Helpers\Tools;
use App\Http\Controllers\Controller;

use App\Models\CertificacoesDeSistemas;

class CertificacoesDeSistemasController extends Controller
{
    public function index()
    {
        $registro = CertificacoesDeSistemas::first();

        return view('painel.certificacoes-de-sistemas.edit', compact('registro'));
    }

    public function update(CertificacoesRequest $request)
    {
        try {
            $registro = CertificacoesDeSistemas::first();
            $input = $request->all();

            if(isset($input['remove_documento'])){
                Tools::removeFileUpload($registro->foto, 'certificacoes-de-sistemas/');
                $registro->foto = false;
            }
            if (!empty($input['foto'])) {
                Tools::removeFileUpload($registro->foto, 'certificacoes-de-sistemas/');
                $input['foto'] = Tools::fileUpload($input['foto'], 'certificacoes-de-sistemas/');
            }
            
            unset($input['remove_documento']);
            $registro->update($input);

            return redirect()->route('painel.certificacoes-de-sistemas.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CertificacoesInmetroController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CertificacoesRequest;
use App\Http\Controllers\Controller;
use App\Helpers\Tools;
use App\Models\CertificacoesInmetro;

class CertificacoesInmetroController extends Controller
{
    public function index()
    {
        $registro = CertificacoesInmetro::first();

        return view('painel.certificacoes-inmetro.edit', compact('registro'));
    }

    public function update(CertificacoesRequest $request)
    {
        try {
            $input = $request->all();
            $registro = CertificacoesInmetro::first();
            $registro->update($input);

            return redirect()->route('painel.certificacoes-inmetro.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CertificacoesInmetroItemController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Http\Requests\CertificacoesItemRequest;
use App\Models\CertificacoesInmetro;
use App\Models\CertificacoesInmetroItem;
use App\Helpers\Tools;

class CertificacoesInmetroItemController extends Controller
{

    public function index(){

        
        // $items = CertificacoesInmetroItem::ordenados()->get();
        $items = CertificacoesInmetroItem::orderBy('ordem', 'asc')->get();

        return view('painel.certificacoes-inmetro.items.index', compact('items'));
    }

    public function create()
    {
        $registro = "";
        return view('painel.certificacoes-inmetro.items.create', compact('registro'));
    }

    public function store(CertificacoesItemRequest $request, CertificacoesInmetroItem $registro)
    {
        try{
            $input = $request->all();

            // if(isset($input['foto'])) $input['foto'] = Tools::fileUpload($input['foto'],'certificacoes-inmetro/');
            if(isset($input['foto'])) $input['foto'] = CertificacoesInmetroItem::uploadImagem1();
            if(!empty($input['documento'])) $input['documento'] = Tools::fileUpload($input['documento'],'certificacoes-inmetro/');

            $input['slug'] = str_slug($input['titulo_conteudo_pt']);
            $registro->create($input);

            return redirect()->route('painel.certificacoes-inmetro-item.index')->with('success', 'Registro cadastrado com sucesso.');
        }catch(\Exception $e){
            return back()->withErrors(['Error ao cadastrar registro. ' . $e->getMessage()]);
        }
    }

    public function edit($id){
        $registro = CertificacoesInmetroItem::find($id);
        return view('painel.certificacoes-inmetro.items.update', compact('registro'));
    }

    public function update(CertificacoesItemRequest $request, CertificacoesInmetroItem $registro, $id){
        try{
            $input = $request->all();
            
            if(isset($input['remove_documento'])){
                $input['foto'] = "";
                $input['documento'] = "";
            }else{
                // if(isset($input['foto'])) $input['foto'] = Tools::fileUpload($input['foto'],'certificacoes-inmetro/');
                if(isset($input['foto'])) $input['foto'] = CertificacoesInmetroItem::uploadImagem1();
                if(!empty($input['documento'])) $input['documento'] = Tools::fileUpload($input['documento'],'certificacoes-inmetro/');
            }

            $input['slug'] = str_slug($input['titulo_conteudo_pt']);
            unset($input['remove_documento']);

            $registro->find($id)->update($input);

            return redirect()->route('painel.certificacoes-inmetro-item.index')->with('success', 'Registro atualizado com sucesso.');
        }catch(\Exception $e){
            return back()->withErrors(['Error ao cadastrar registro. ' . $e->getMessage()]);
        }
    }

    public function destroy(CertificacoesInmetroItem $registro, $id){
        try{
            $registro->find($id)->delete();
            return back()->with('success', 'Registro excluído com sucesso.');
        }catch(\Exception $e){
            return back()->withErrors(['Error ao deletar registro. ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CertificacoesProvenceController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\CertificacoesRequest;
use App\Models\CertificacoesProvence;
use App\Helpers\Tools;

class CertificacoesProvenceController extends Controller
{
    public function index()
    {
        $registro = CertificacoesProvence::first();

        return view('painel.certificacoes-provence.edit', compact('registro'));
    }

    public function update(CertificacoesRequest $request, CertificacoesProvence $registro)
    {
        try {
            $input = $request->all();

            $registro->first()->update($input);

            return redirect()->route('painel.certificacoes-provence.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CertificadoSistemasImagensController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CertificadoSistemasImagensRequest;
use App\Http\Controllers\Controller;

use App\Models\CertificadoSistemasImagens;

class CertificadoSistemasImagensController extends Controller
{
    public function index()
    {
        $registros = CertificadoSistemasImagens::orderBy('ordem', 'asc')->get();

        return view('painel.certificado-de-sistemas-imagens.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.certificado-de-sistemas-imagens.create');
    }

    public function store(CertificadoSistemasImagensRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = CertificadoSistemasImagens::upload_imagem();

            CertificadoSistemasImagens::create($input);

            return redirect()->route('painel.certificado-de-sistemas-imagens.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(CertificadoSistemasImagens $registro)
    {
        return view('painel.certificado-de-sistemas-imagens.edit', compact('registro'));
    }

    public function update(CertificadoSistemasImagensRequest $request, CertificadoSistemasImagens $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = CertificadoSistemasImagens::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.certificado-de-sistemas-imagens.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(CertificadoSistemasImagens $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.certificado-de-sistemas-imagens.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/resources/views/painel/propostas-config/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>      
        <h2>Nova página</h2>
    </legend>

    {!! Form::model($registro,[
        'route'  => ['painel.propostas-configuracoes.store'],
        'method' => 'post',
        'files'  => true])
    !!}

    @include('painel.propostas-config.form', ['submitText' => 'Cadastrar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/propostas-config/form.blade.php
@include('painel.common.flash')

<div class="form-row">
    <div class="form-group col-md-12 col-sm-12">
        {!! Form::label('titulo', 'Título da página') !!}
        {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
    </div>
    <div class="form-group col-md-12 col-sm-12" style="display: flex; flex-direction: column;">
        {!! Form::label('categoria', 'Categoria') !!}
        {!! Form::select('categoria', [
            'como_conheceu' => 'Como conheceu a provence', 
            'situacao_cert' => 'Situação da Certificação',
            'tipo_cert' => 'Tipo de Certificação',
            'modelo_cert' => 'Modelo de Certificação'
        ], (isset($registro->categoria))?$registro->categoria:'', 
        ['style' => 'height: 50px;']); !!}
    </div>
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success', 'style' => 'margin-left: 15px']) !!}

laravel/resources/views/painel/propostas-config/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>
            Configurações Proposta
            <a href="{{ route('painel.propostas-configuracoes.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Item</a>
        </h2>
    </legend>

    @if(!count($registro))
        <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
        <!-- Como conheceu a provence ---------->
        <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="novidades">
            <thead>
                <tr>
                    <th style="width: 80%">Como conheceu a Provence</th>
                    <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
                </tr>
            </thead>

            <tbody>
            @foreach ($registro as $item)
                @if ($item->categoria == "como_conheceu")
                    <tr class="tr-row" id="{!! $item->id !!}">
                        <td>    
                            <li>{!! $item->titulo !!}</li>    
                        </td>
                        <td>
                            <div class="">
                                <a href="{{ route('painel.propostas-configuracoes.edit', $item->id ) }}" class="btn btn-primary btn-sm btn-block" style="margin-bottom:10px;">
                                    <span class="glyphicon glyphicon-pencil" ></span>Editar
                                </a>
                            
                                {!! Form::open([
                                    'route'  => ['painel.propostas-configuracoes.destroy', $item->id],
                                    'method' => 'delete'
                                ]) !!}
                                <button type="submit" class="btn btn-danger btn-sm btn-block btn-delete"><span class="glyphicon glyphicon-remove" ></span>Excluir</button>
                                {!! Form::close() !!}
                            </div>

                        </td>
                    </tr>
                @endif
            @endforeach
            </tbody>
        </table>

        <!-- Situação da Certificação ---------->
        <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="novidades">
            <thead>
                <tr>
                    <th style="width: 80%">Situação da Certificação</th>
                    <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
                </tr>
            </thead>

            <tbody>
            @foreach ($registro as $item)
                @if ($item->categoria == "situacao_cert")
                    <tr class="tr-row" id="{!! $item->id !!}">
                        <td>    
                            <li>{!! $item->titulo !!}</li>    
                        </td>
                        <td>
                            <div class="">
                                <a href="{{ route('painel.propostas-configuracoes.edit', $item->id ) }}" class="btn btn-primary btn-sm btn-block" style="margin-bottom:10px;">
                                    <span class="glyphicon glyphicon-pencil" ></span>Editar
                                </a>
                            
                                {!! Form::open([
                                    'route'  => ['painel.propostas-configuracoes.destroy', $item->id],
                                    'method' => 'delete'
                                ]) !!}
                                <button type="submit" class="btn btn-danger btn-sm btn-block btn-delete"><span class="glyphicon glyphicon-remove" ></span>Excluir</button>
                                {!! Form::close() !!}
                            </div>

                        </td>
                    </tr>
                @endif
            @endforeach
            </tbody>
        </table>

        <!-- Tipo de Certificação ---------->
        <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="novidades">
            <thead>
                <tr>
                    <th style="width: 80%">Tipo de Certificação</th>
                    <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
                </tr>
            </thead>

            <tbody>
            @foreach ($registro as $item)
                @if ($item->categoria == "tipo_cert")
                    <tr class="tr-row" id="{!! $item->id !!}">
                        <td>    
                            <li>{!! $item->titulo !!}</li>    
                        </td>
                        <td>
                            <div class="">
                                <a href="{{ route('painel.propostas-configuracoes.edit', $item->id ) }}" class="btn btn-primary btn-sm btn-block" style="margin-bottom:10px;">
                                    <span class="glyphicon glyphicon-pencil" ></span>Editar
                                </a>
                            
                                {!! Form::open([
                                    'route'  => ['painel.propostas-configuracoes.destroy', $item->id],
                                    'method' => 'delete'
                                ]) !!}
                                <button type="submit" class="btn btn-danger btn-sm btn-block btn-delete"><span class="glyphicon glyphicon-remove" ></span>Excluir</button>
                                {!! Form::close() !!}
                            </div>

                        </td>
                    </tr>
                @endif
            @endforeach
            </tbody>
        </table>

        <!-- Modelo de Certificação ---------->
        <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="novidades">
            <thead>
                <tr>
                    <th style="width: 80%">Modelo de Certificação</th>
                    <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
                </tr>
            </thead>

            <tbody>
            @foreach ($registro as $item)
                @if ($item->categoria == "modelo_cert")
                    <tr class="tr-row" id="{!! $item->id !!}">
                        <td>    
                            <li>{!! $item->titulo !!}</li>    
                        </td>
                        <td>
                            <div class="">
                                <a href="{{ route('painel.propostas-configuracoes.edit', $item->id ) }}" class="btn btn-primary btn-sm btn-block" style="margin-bottom:10px;">
                                    <span class="glyphicon glyphicon-pencil" ></span>Editar
                                </a>
                            
                                {!! Form::open([
                                    'route'  => ['painel.propostas-configuracoes.destroy', $item->id],
                                    'method' => 'delete'
                                ]) !!}
                                <button type="submit" class="btn btn-danger btn-sm btn-block btn-delete"><span class="glyphicon glyphicon-remove" ></span>Excluir</button>
                                {!! Form::close() !!}
                            </div>

                        </td>
                    </tr>
                @endif
            @endforeach
            </tbody>
        </table>
    @endif

@endsection

laravel/resources/views/painel/propostas-config/update.blade.php
@extends('painel.common.template')

@section('content')

    <legend>      
        <h2>Editar página</h2>
    </legend>

    {!! Form::model($registro,[
        'route'  => ['painel.propostas-configuracoes.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.propostas-config.form', ['submitText' => 'Atualizar'])

    {!! Form::close() !!}

@endsection