laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('certificacoes-provence', 'CertificacoesController@provence')->name('certificacoes-provence');
    Route::get('certificacoes-provence/{internal?}', 'CertificacoesController@provencePaginaInterna')->name('provence-interna');
    Route::get('certificacoes-inmetro', 'CertificacoesController@inmetro')->name('certificacoes-inmetro');
    Route::get('certificacoes-inmetro/{internal?}', 'CertificacoesController@inmetroPaginaInterna')->name('inmetro-interna');
    Route::get('certificacoes-de-sistemas', 'CertificacoesController@deSistemas')->name('certificacoes-de-sistemas');
    Route::get('perfil-empresa', 'HomeController@perfilEmpresa')->name('perfil-empresa');
    Route::get('nossos-servicos', 'HomeController@nossosServicos')->name('nossos-servicos');
    Route::get('suporte-e-novidades/documentos-regulamentares', 'NovidadesController@documentosRegulamentares')->name('documentos-regulamentares');
    Route::get('suporte-e-novidades/perguntas-frequentes', 'NovidadesController@perguntasFrequentes')->name('perguntas-frequentes');
    Route::get('suporte-e-novidades/novidades', 'NovidadesController@novidades')->name('informacoes-e-novidades');
    Route::get('novidades/{internal?}', 'NovidadesController@novidadesPaginaInterna')->name('novidades-interna');
    Route::get('fale-conosco', 'FaleConoscoController@index')->name('fale-conosco');
    Route::post('fale-conosco', 'FaleConoscoController@post')->name('fale-conosco-post');
    Route::get('politica-de-privacidade', 'HomeController@politicaDePrivacidade')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');
    Route::post('propostas-post', 'PropostasController@post')->name('propostas-post');
    
    // Idiomas
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if (in_array($idioma, ['pt', 'en'])) {
            Session::put('locale', $idioma);
        }
        return redirect()->back();
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        Route::group(['middleware' => 'admin'], function() {
            /* GENERATED ROUTES */
            Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
            Route::resource('certificacoes-provence', 'CertificacoesProvenceController', ['only' => ['index', 'update']]);
            Route::resource('certificacoes-provence-item', 'CertificacoesProvenceItemController');
            Route::resource('certificacoes-inmetro', 'CertificacoesInmetroController', ['only' => ['index', 'update']]);
            Route::resource('certificacoes-inmetro-item', 'CertificacoesInmetroItemController');
            Route::resource('certificacoes-de-sistemas', 'CertificacoesDeSistemasController', ['only' => ['index', 'update']]);
            Route::resource('perfil-empresa', 'PerfilEmpresaController', ['only' => ['index', 'update']]);
            Route::resource('nossos-servicos', 'NossosServicosController', ['only' => ['index', 'update']]);
            Route::resource('documentos-regulamentares', 'DocumentosRegulamentaresController');
            Route::resource('perguntas-frequentes', 'PerguntasFrequentesController');
            Route::resource('informacoes-e-novidades', 'InformacoesNovidadesController');
            Route::resource('fale-conosco', 'FaleConoscoController', ['only' => ['index', 'update']]);
            Route::resource('depoimentos', 'DepoimentosController');
            Route::resource('propostas', 'PropostasController');
            Route::resource('propostas-configuracoes', 'PropostasConfigController');
            Route::resource('validacao-certificados', 'ValidacaoController');
            Route::resource('certificados', 'CertificadosDeValidacaoController');
            Route::resource('banners', 'BannersController');
            Route::resource('certificado-de-sistemas-imagens', 'CertificadoSistemasImagensController');

            Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

            Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
            Route::resource('contato', 'ContatoController');
            Route::get('contato/recebidos', 'ContatosRecebidosController@index')->name('painel.contato.recebidos');
            Route::resource('recebidos', 'RecebidosController');

            Route::resource('usuarios', 'UsuariosController');
            Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
            Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');

            Route::post('ckeditor-upload', 'PainelController@imageUpload');
            Route::post('order', 'PainelController@order');
            Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

            Route::get('generator', 'GeneratorController@index')->name('generator.index');
            Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
        });
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });

    Route::get('/{slug}', 'ValidacaoController@index')->name('validacao-cliente');
});

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/CertificacoesDeSistemasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Requests\CertificacoesRequest;
use App\Helpers\Tools;
use App\Http\Controllers\Controller;

use App\Models\CertificacoesDeSistemas;

class CertificacoesDeSistemasController extends Controller
{
    public function index()
    {
        $registro = CertificacoesDeSistemas::first();

        return view('painel.certificacoes-de-sistemas.edit', compact('registro'));
    }

    public function update(CertificacoesRequest $request)
    {
        try {
            $registro = CertificacoesDeSistemas::first();
            $input = $request->all();

            if(isset($input['remove_documento'])){
                Tools::removeFileUpload($registro->foto, 'certificacoes-de-sistemas/');
                $registro->foto = false;
            }
            if (!empty($input['foto'])) {
                Tools::removeFileUpload($registro->foto, 'certificacoes-de-sistemas/');
                $input['foto'] = Tools::fileUpload($input['foto'], 'certificacoes-de-sistemas/');
            }
            
            unset($input['remove_documento']);
            $registro->update($input);

            return redirect()->route('painel.certificacoes-de-sistemas.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CertificacoesInmetroController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CertificacoesRequest;
use App\Http\Controllers\Controller;
use App\Helpers\Tools;
use App\Models\CertificacoesInmetro;

class CertificacoesInmetroController extends Controller
{
    public function index()
    {
        $registro = CertificacoesInmetro::first();

        return view('painel.certificacoes-inmetro.edit', compact('registro'));
    }

    public function update(CertificacoesRequest $request)
    {
        try {
            $input = $request->all();
            $registro = CertificacoesInmetro::first();
            $registro->update($input);

            return redirect()->route('painel.certificacoes-inmetro.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CertificacoesInmetroItemController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Http\Requests\CertificacoesItemRequest;
use App\Models\CertificacoesInmetro;
use App\Models\CertificacoesInmetroItem;
use App\Helpers\Tools;

class CertificacoesInmetroItemController extends Controller
{

    public function index(){

        
        // $items = CertificacoesInmetroItem::ordenados()->get();
        $items = CertificacoesInmetroItem::orderBy('ordem', 'asc')->get();

        return view('painel.certificacoes-inmetro.items.index', compact('items'));
    }

    public function create()
    {
        $registro = "";
        return view('painel.certificacoes-inmetro.items.create', compact('registro'));
    }

    public function store(CertificacoesItemRequest $request, CertificacoesInmetroItem $registro)
    {
        try{
            $input = $request->all();

            // if(isset($input['foto'])) $input['foto'] = Tools::fileUpload($input['foto'],'certificacoes-inmetro/');
            if(isset($input['foto'])) $input['foto'] = CertificacoesInmetroItem::uploadImagem1();
            if(!empty($input['documento'])) $input['documento'] = Tools::fileUpload($input['documento'],'certificacoes-inmetro/');

            $input['slug'] = str_slug($input['titulo_conteudo_pt']);
            $registro->create($input);

            return redirect()->route('painel.certificacoes-inmetro-item.index')->with('success', 'Registro cadastrado com sucesso.');
        }catch(\Exception $e){
            return back()->withErrors(['Error ao cadastrar registro. ' . $e->getMessage()]);
        }
    }

    public function edit($id){
        $registro = CertificacoesInmetroItem::find($id);
        return view('painel.certificacoes-inmetro.items.update', compact('registro'));
    }

    public function update(CertificacoesItemRequest $request, CertificacoesInmetroItem $registro, $id){
        try{
            $input = $request->all();
            
            if(isset($input['remove_documento'])){
                $input['foto'] = "";
                $input['documento'] = "";
            }else{
                // if(isset($input['foto'])) $input['foto'] = Tools::fileUpload($input['foto'],'certificacoes-inmetro/');
                if(isset($input['foto'])) $input['foto'] = CertificacoesInmetroItem::uploadImagem1();
                if(!empty($input['documento'])) $input['documento'] = Tools::fileUpload($input['documento'],'certificacoes-inmetro/');
            }

            $input['slug'] = str_slug($input['titulo_conteudo_pt']);
            unset($input['remove_documento']);

            $registro->find($id)->update($input);

            return redirect()->route('painel.certificacoes-inmetro-item.index')->with('success', 'Registro atualizado com sucesso.');
        }catch(\Exception $e){
            return back()->withErrors(['Error ao cadastrar registro. ' . $e->getMessage()]);
        }
    }

    public function destroy(CertificacoesInmetroItem $registro, $id){
        try{
            $registro->find($id)->delete();
            return back()->with('success', 'Registro excluído com sucesso.');
        }catch(\Exception $e){
            return back()->withErrors(['Error ao deletar registro. ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CertificacoesProvenceController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\CertificacoesRequest;
use App\Models\CertificacoesProvence;
use App\Helpers\Tools;

class CertificacoesProvenceController extends Controller
{
    public function index()
    {
        $registro = CertificacoesProvence::first();

        return view('painel.certificacoes-provence.edit', compact('registro'));
    }

    public function update(CertificacoesRequest $request, CertificacoesProvence $registro)
    {
        try {
            $input = $request->all();

            $registro->first()->update($input);

            return redirect()->route('painel.certificacoes-provence.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CertificadoSistemasImagensController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CertificadoSistemasImagensRequest;
use App\Http\Controllers\Controller;

use App\Models\CertificadoSistemasImagens;

class CertificadoSistemasImagensController extends Controller
{
    public function index()
    {
        $registros = CertificadoSistemasImagens::orderBy('ordem', 'asc')->get();

        return view('painel.certificado-de-sistemas-imagens.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.certificado-de-sistemas-imagens.create');
    }

    public function store(CertificadoSistemasImagensRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = CertificadoSistemasImagens::upload_imagem();

            CertificadoSistemasImagens::create($input);

            return redirect()->route('painel.certificado-de-sistemas-imagens.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(CertificadoSistemasImagens $registro)
    {
        return view('painel.certificado-de-sistemas-imagens.edit', compact('registro'));
    }

    public function update(CertificadoSistemasImagensRequest $request, CertificadoSistemasImagens $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = CertificadoSistemasImagens::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.certificado-de-sistemas-imagens.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(CertificadoSistemasImagens $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.certificado-de-sistemas-imagens.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">

    <div class="container">

        <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">

                <span class="sr-only">Toggle navigation</span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

            </button>

            <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>

        </div>



        <div id="navbar" class="navbar-collapse collapse">

            @include('painel.common.nav')



            <ul class="nav navbar-nav navbar-right">

                <li class="dropdown @if(Tools::routeIs(['painel.usuarios*', 'painel.configuracoes*', 'painel.politica-de-privacidade*', 'painel.aceite-de-cookies*'])) active @endif">

                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">

                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>

                        <b class="caret"></b>

                    </a>

                    <ul class="dropdown-menu">

                        <li @if(Tools::routeIs('painel.politica-de-privacidade*')) class="active" @endif>

                            <a href="{{ route('painel.politica-de-privacidade.index') }}">Politica de Privacidade</a>

                        </li>

                        <li @if(Tools::routeIs('painel.aceite-de-cookies*')) class="active" @endif>

                            <a href="{{ route('painel.aceite-de-cookies') }}">Aceite de Cookies</a>

                        </li>

                        <li @if(Tools::routeIs('painel.configuracoes*')) class="active" @endif>

                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>

                        </li>

                        <li @if(Tools::routeIs('painel.usuarios*')) class="active" @endif>

                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>

                        </li>

                        <li><a href="{{ route('logout') }}">Logout</a></li>

                    </ul>

                </li>

            </ul>

        </div>

    </div>

</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">

    <li @if(Tools::routeIs('painel.home*')) class="active" @endif>

        <a href="{{ route('painel.home.index') }}">Home</a>

    </li>

    <li class="dropdown @if(Tools::routeIs('painel.certificacoes-inmetro*')) active @endif">

        <a href="#" class="dropdown-toggle" data-toggle="dropdown">

            Cert. Inmetro

            <b class="caret"></b>

        </a>

        <ul class="dropdown-menu">

            <li @if(Tools::routeIs('painel.certificacoes-inmetro.index')) class="active" @endif>

                <a href="{{ route('painel.certificacoes-inmetro.index') }}">Certificacões Inmetro</a>

            </li>

            <li class="divider"></li>

            <li @if(Tools::routeIs('painel.certificacoes-inmetro-item.index')) class="active" @endif>

                <a href="{{ route('painel.certificacoes-inmetro-item.index') }}">Páginas</a>

            </li>

        </ul>

    </li>

    <li class="dropdown @if(Tools::routeIs('painel.certificacoes-de-sistemas*')) active @endif">

        <a href="#" class="dropdown-toggle" data-toggle="dropdown">

            Cert. de Sistemas

            <b class="caret"></b>

        </a>

        <ul class="dropdown-menu">

                <li @if(Tools::routeIs('painel.certificacoes-de-sistemas*')) class="active" @endif>

                    <a href="{{ route('painel.certificacoes-de-sistemas.index') }}">Cert. de Sistemas</a>

                </li>

                <li class="divider"></li>

                <li @if(Tools::routeIs('painel.certificado-de-sistemas-imagens*')) class="active" @endif>

                    <a href="{{ route('painel.certificado-de-sistemas-imagens.index') }}">Imagens</a>

                </li>

            </ul>

        </li>


    <li class="dropdown @if(Tools::routeIs('painel.certificacoes-provence*')) active @endif">

        <a href="#" class="dropdown-toggle" data-toggle="dropdown">

            Cert. Provence

            <b class="caret"></b>

        </a>

        <ul class="dropdown-menu">

            <li @if(Tools::routeIs('painel.certificacoes-provence.index')) class="active" @endif>

                <a href="{{ route('painel.certificacoes-provence.index') }}">Certificacões Provence</a>

            </li>

            <li class="divider"></li>

            <li @if(Tools::routeIs('painel.certificacoes-provence-item.index')) class="active" @endif>

                <a href="{{ route('painel.certificacoes-provence-item.index') }}">Páginas</a>

            </li>

        </ul>

    </li>

    <li @if(Tools::routeIs('painel.perfil-empresa*')) class="active" @endif>

        <a href="{{ route('painel.perfil-empresa.index') }}">Quem Somos</a>

    </li>

    <li @if(Tools::routeIs('painel.nossos-servicos*')) class="active" @endif>

        <a href="{{ route('painel.nossos-servicos.index') }}">Nossos Serviços</a>

    </li>

    <li class="dropdown @if(Tools::routeIs('painel.informacoes-e-novidades*')) active @endif">

        <a href="#" class="dropdown-toggle" data-toggle="dropdown">

            Novidades

            <b class="caret"></b>

        </a>

        <ul class="dropdown-menu">

            <li @if(Tools::routeIs('painel.documentos-regulamentares.index')) class="active" @endif>

                <a href="{{ route('painel.documentos-regulamentares.index') }}">Documentos Relugamentares</a>

            </li>

            <li @if(Tools::routeIs('painel.perguntas-frequentes.index')) class="active" @endif>

                <a href="{{ route('painel.perguntas-frequentes.index') }}">Perguntas Frequentes</a>

            </li>

            <li @if(Tools::routeIs('painel.informacoes-e-novidades.index')) class="active" @endif>

                <a href="{{ route('painel.informacoes-e-novidades.index') }}">Informações e Novidades</a>

            </li>

        </ul>

    </li>

    <li @if(Tools::routeIs('painel.depoimentos*')) class="active" @endif>

        <a href="{{ route('painel.depoimentos.index') }}">Depoimentos</a>

    </li>

    <li @if(Tools::routeIs('painel.fale-conosco*')) class="active" @endif>

        <a href="{{ route('painel.fale-conosco.index') }}">Fale Conosco</a>

    </li>


    <li @if(Tools::routeIs('painel.contato.recebidos*')) class="active" @endif>

        <a href="{{ route('painel.recebidos.index') }}">Contatos Recebidos</a>

    </li>



    <li class="dropdown @if(Tools::routeIs('painel.propostas*')) active @endif">

        <a href="#" class="dropdown-toggle" data-toggle="dropdown">

            Propostas

            <b class="caret"></b>

        </a>

        <ul class="dropdown-menu">

            <li @if(Tools::routeIs('painel.propostas.index')) class="active" @endif>

                <a href="{{ route('painel.propostas.index') }}">Propostas</a>

            </li>

            <li class="divider"></li>

            <li @if(Tools::routeIs('painel.propostas-configuracoes.index')) class="active" @endif>

                <a href="{{ route('painel.propostas-configuracoes.index') }}">Propostas Config</a>

            </li>

        </ul>

    </li>

    <li @if(Tools::routeIs('painel.validacao-certificados*')) class="active" @endif>

        <a href="{{ route('painel.validacao-certificados.index') }}">Validações | Certificados</a>

    </li>

</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('app.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/vendor.painel.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel.css') }}">
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/js/vendor.painel.js') }}"></script>
    <script src="{{ asset('assets/js/painel.js') }}"></script>

    <script>
        function removeImage(id){
            var foto = $('.btn-remove-image').val();

                $.ajax({
                    url: "painel/imovel/removeFile?foto="+foto+"&id="+id,
                    type: 'post',
                    dataType: 'json',
                    contentType: false,
                    processData: false,
                    success: function(response){
                        alert(response);
                        console.log(response);
                    },
                    error: function(response){
                        console.log('error');
                    },
                });
        }
</script>


@yield('script')
</body>
</html>